name: override_text_scale_factor
description: This package provides a widget that overrides the textScaleFactor given by MediaQuery.
version: 0.0.3

homepage: https://github.com/sandstrom99/override_text_scale_factor

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter

flutter:

